# Generated by Django 5.0.6 on 2024-07-08 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={"verbose_name": "Player", "verbose_name_plural": "Players"},
        ),
    ]
