# Generated by Django 5.0.6 on 2024-07-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_platform_game_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
