# Generated by Django 5.0.6 on 2024-07-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_alter_player_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="genre_images"),
        ),
    ]
