# Generated by Django 5.0.6 on 2024-07-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_alter_player_first_name_alter_player_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="age",
        ),
        migrations.AddField(
            model_name="player",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
