# Generated by Django 5.0.6 on 2024-07-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_genre_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="publisher_images"
            ),
        ),
    ]
