# Generated by Django 5.0.6 on 2024-07-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_publisher_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="completed_games",
            field=models.ManyToManyField(
                blank=True, related_name="completed_by", to="game.game"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="wishlist_games",
            field=models.ManyToManyField(
                blank=True, related_name="wishlisted_by", to="game.game"
            ),
        ),
    ]
