# Generated by Django 5.0.6 on 2024-07-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_alter_genre_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="genre_images"),
        ),
    ]
