# Generated by Django 5.0.6 on 2024-07-16 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_alter_genre_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="genre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game.genre"
            ),
        ),
    ]
