# Generated by Django 5.0.6 on 2024-07-09 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="players",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="games", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
