# Generated by Django 5.0.6 on 2024-07-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_alter_game_genre"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publisher",
            options={"ordering": ["name"]},
        ),
    ]
