# Generated by Django 5.0.6 on 2024-07-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_alter_game_players"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="platform",
        ),
        migrations.AddField(
            model_name="game",
            name="platforms",
            field=models.JSONField(default=list),
        ),
    ]
