# Generated by Django 5.0.6 on 2024-07-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_alter_publisher_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="description",
            field=models.TextField(),
        ),
    ]
