# Generated by Django 5.0.6 on 2024-07-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_remove_game_platform_game_platforms"),
    ]

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="game",
            name="platforms",
        ),
        migrations.AddField(
            model_name="game",
            name="platforms",
            field=models.ManyToManyField(related_name="games", to="game.platform"),
        ),
    ]
