# Generated by Django 5.0.6 on 2024-07-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_platform_remove_game_platforms_game_platforms"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="platform",
            options={"ordering": ["name"]},
        ),
        migrations.RenameField(
            model_name="platform",
            old_name="title",
            new_name="name",
        ),
    ]
